show databases;
create database DFE4;
create database DFE5;
drop database DFE5;
use DFE4;
show tables;
create database Bootcamp;
use Bootcamp;
create table Trainer(trainerID INT PRIMARY KEY, trainerName VARCHAR(15), trainerDOB DATE, Salary DECIMAL(5,5));
DESCRIBE TRAINER;
INSERT INTO TRAINER(trainerID, trainerName, trainerDOB, Salary) Values (1, "Zak", '1996-09-20', 20.3);
drop table trainer;
create table Trainer(trainerID INT PRIMARY KEY, trainerName VARCHAR(15), trainerDOB DATE, Salary DECIMAL(5,5));
INSERT INTO TRAINER(trainerID, trainerName, trainerDOB, Salary) Values (1, "Zak", '1996-09-20', 1.1);
drop table trainer;
create table Trainer(trainerID INT PRIMARY KEY, trainerName VARCHAR(15), trainerDOB DATE, Salary DECIMAL(20,2));
INSERT INTO TRAINER(trainerID, trainerName, trainerDOB, Salary) Values (1, "Zak", '1996-09-20', 20.3);
INSERT INTO TRAINER(trainerID, trainerName, trainerDOB, Salary) Values (2, "Bob", '1980-07-07', 15.2);
INSERT INTO TRAINER(trainerID, trainerName, trainerDOB, Salary) Values (3, "Suzie", '1979-03-28', 24.2);
select * from trainer;
create table student(stdID int primary key, fName varchar(15), lName varchar(15), Module varchar(15), trainerNum int); 
drop table student;
create table student(stdID int primary key, fName varchar(15), lName varchar(15), Module varchar(15), trainerNum int); 
drop table student;
create table student(stdID int primary key, fName varchar(15), lName varchar(15), Module varchar(15), trainerNum int, FOREIGN KEY (trainerNum) REFERENCES trainer(trainerID) );
insert into student(stdID, fName, lName, Module, trainerNum) values (1,"Mark", "Robinson","SQL", 1),(2,"John", "Bell","SQL", 1),(3,"Betty", "Coleman","HTML", 2); 
select * from student;
insert into student(stdID, fName, lName, Module, trainerNum) values (4,"Olivia", "Kurt","CSS", 3),(5,"Jack", "Norman","HTML", 2);

