show databases; -- will list all available databases in MySQL
SHOW DATABASES;
CREATE DATABASE DFE5;
SHOW DATABASES;
USE DFE5;

CREATE DATABASE TEST1;
CREATE DATABASE TEST2;
CREATE DATABASE TEST3;
USE TEST2;
SHOW TABLES;